% add
put 1 + 1 % 2
put 1.1 + 1.2 % 2.3
put 1 + 1.2 % 2.2

% minus
put 1 - 1 % 0
put 1.1 - 1.2 % -0.1
put 1 - 1.2 % -0.2

% multiply
put 4 * 2 % 8
put 1.5 * 1.2 % 1 .8 
put 2 * 1.2 % 2.4

% divide
put 6 / 3 % 2
put 2.4 / 1.2 % 2
put 15 / 1.5 % 10
put 4.3 / 2 % 2.15

% mod
put 3 mod 2 % 1
put 4 mod 2.1 % 0

put 1 + -1 + (3 + 1) * 2 + 4 * 3 + 1 % 21
put 1.0 + 1.1
put 1 + -1

% Warning
put 1.5 / 0 % divide 0